### ISSUE TITLE
ES6 syntax should be compiled

### ISSUE THREAD

**Issue by alexmasny** [Dallian/immutableql#2]
Got an error during the `yarn build` of the `create-react-app`. 

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file: 
> ```
> ./node_modules/immutableql/lib/index.js:1 
> ```
> Read more here: http://bit.ly/2tRViJ9
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Seems, that ES6 code needs to be compiled into ES5 (hello, modern web...):

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

Thus, it might be the case, to use some bundler with babel. Look at Rollup:

> Use webpack for apps, and Rollup for libraries
> [Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)

**Comment by Vladislav-Boiko** [comment]
Hi, indeed I completely overlooked  it, now fixed it in
commit 53c938d3c797a575168dc8503464f3a24b7be8a5

thank you for reporting!
